# Generated by Django 3.2.2 on 2024-05-17 14:27

import autograder.core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_instructorfile__remove_in_v5_file_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_limit_reset_timezone',
            field=models.TextField(default='UTC', help_text='A string representing the timezone to use when computing\n            how many submissions a group has made in a 24 hour period.', validators=[autograder.core.utils.validate_timezone]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(help_text='\n            The Group that this submission belongs to. Note\n            that this field indirectly links this Submission object to a\n            Project.\n            This field is REQUIRED.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.group'),
        ),
    ]
