# Generated by Django 3.2.2 on 2024-08-06 16:26

import autograder.core.fields
import autograder.core.models.ag_test.ag_test_case
import autograder.core.models.ag_test.ag_test_suite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_test_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestcase',
            name='past_limit_submission_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.ag_test.ag_test_case._past_limit_fdbk, serializable_class=autograder.core.models.ag_test.ag_test_case.AGTestCaseFeedbackConfig),
        ),
        migrations.AlterField(
            model_name='agtestsuite',
            name='past_limit_submission_fdbk_config',
            field=autograder.core.fields.ValidatedJSONField(default=autograder.core.models.ag_test.ag_test_suite.AGTestSuiteFeedbackConfig, serializable_class=autograder.core.models.ag_test.ag_test_suite.AGTestSuiteFeedbackConfig),
        ),
    ]
