# Generated by Django 3.2.2 on 2024-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20240806_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='soft_extended_due_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When this field is set, it indicates the extended due date\n            that is visible to members of the group. Members of the group will\n            still be able to submit after this date but before the\n            extended_due_date.\n            Default value: None', null=True),
        ),
    ]
