# Generated by Django 3.2.2 on 2024-08-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20240806_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='agtestcase',
            name='internal_admin_notes',
            field=models.TextField(blank=True, help_text='Additional information for admins. Shown only when editing the test case.'),
        ),
        migrations.AddField(
            model_name='agtestcommand',
            name='internal_admin_notes',
            field=models.TextField(blank=True, help_text='Additional information for admins. Shown only when editing the command.'),
        ),
        migrations.AddField(
            model_name='agtestsuite',
            name='internal_admin_notes',
            field=models.TextField(blank=True, help_text='Additional information for admins. Shown only when editing the test suite.'),
        ),
    ]
