# Generated by Django 3.2.25 on 2024-11-19 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0108_internal_admin_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='LateDaysRemaining',
            old_name='_extra_late_days_granted',
            new_name='extra_late_days',
        ),
        migrations.RemoveField(
            model_name='LateDaysRemaining',
            name='old_late_days_remaining'
        ),
        migrations.RemoveField(
            model_name='LateDaysRemaining',
            name='late_days_used'
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-pk', '-timestamp']},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['group', 'timestamp'], name='core_submis_group_i_160046_idx'),
        ),
        migrations.RenameModel(
            old_name='LateDaysRemaining',
            new_name='ExtraLateDays'
        ),
    ]
