# Generated by Django 3.2.2 on 2024-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_group_soft_extended_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hard_extended_due_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When this field is set, it indicates that members\n            of this submission group can submit until this specified\n            date, overriding the project closing time.\n            Default value: None', null=True),
        ),
    ]
