# Generated by Django 3.2.2 on 2024-09-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_internal_admin_notes'),
        ('core', '0109_alter_group_hard_extended_due_date'),
    ]

    operations = [
    ]
