# Generated by Django 3.2.2 on 2024-11-22 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0109_late_days_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extralatedays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_days', to=settings.AUTH_USER_MODEL),
        ),
    ]
