# Generated by Django 3.2.2 on 2024-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_tz_validation_update'),
        ('handgrading', '0012_alter_handgradingrubric_show_only_applied_rubric_to_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handgradingresult',
            name='group',
            field=models.OneToOneField(help_text='The Group that this HandgradingResult is for.', on_delete=django.db.models.deletion.CASCADE, related_name='handgrading_result', to='core.group'),
        ),
    ]
